// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzbIdORbHfyV-4fm19aWCUa90ImsAVsKg',
    appId: '1:457857695730:web:01055958a7296d5c98356b',
    messagingSenderId: '457857695730',
    projectId: 'migna-store',
    authDomain: 'migna-store.firebaseapp.com',
    storageBucket: 'migna-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLr-qeAPDspp5Orj8pPj-ZN1HGBmn87s',
    appId: '1:457857695730:android:62b356280c41994998356b',
    messagingSenderId: '457857695730',
    projectId: 'migna-store',
    storageBucket: 'migna-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVpbimerA-pn4XbfrkZEf3HpmRQYgo9uQ',
    appId: '1:457857695730:ios:6f92d9f7087038de98356b',
    messagingSenderId: '457857695730',
    projectId: 'migna-store',
    storageBucket: 'migna-store.firebasestorage.app',
    iosBundleId: 'com.athem.mignastore',
  );
}
